- name: Create Loopbacks
  cisco.nxos.nxos_interfaces: 
    config:
    - name: "{{ item.value.name }}"
      enabled: true
    state: merged
  loop: "{{ loop_intfs }}"
  loop_control:
    label: "{{ item.value.name }}"
  

- name: Configure Loopback IP addresses
  cisco.nxos.nxos_l3_interfaces:
    config:
      - name: "{{ item.value.name }}" 
        ipv4:
          - address: "{{ loop_ips[0].value.address }}"
  when: loop_ips 
  loop: "{{ loop_intfs }}"
  loop_control: 
    label: "{{ item.value.name }}"
  vars:
    loop_ips:  "{{ query('netbox.netbox.nb_lookup', 'ip-addresses',
                  api_endpoint=nb_api_endpoint,
                  api_filter='interface_id=' ~ item.value.id,
                  token=nb_api_token) }}"

- name: Enabling PIM on Loopback interfaces
  cisco.nxos.nxos_pim_interface:
    interface: "{{ item.value.name }}"
    sparse: yes
  loop: "{{ loop_intfs }}"
  loop_control: 
    label: "{{ item.value.name }}"