---
# vars file for leaf
vlans: "{{ query('netbox.netbox.nb_lookup', 'vlans',
                  api_endpoint=nb_api_endpoint,
                  token=nb_api_token) }}"
vrfs: "{{ query('netbox.netbox.nb_lookup', 'vrfs',
                    api_endpoint=nb_api_endpoint,
                    token=nb_api_token) }}"
svis: "{{ query('netbox.netbox.nb_lookup', 'interfaces',
                      api_endpoint=nb_api_endpoint,
                      api_filter='name__ic=Vlan device=' ~ inventory_hostname,
                      token=nb_api_token) }}"
anygw_svis: "{{ query('netbox.netbox.nb_lookup', 'interfaces',
                      api_endpoint=nb_api_endpoint,
                      api_filter='tag=anycast-gateway device=' ~ inventory_hostname,
                      token=nb_api_token) }}"
svivrf_svis: "{{ query('netbox.netbox.nb_lookup', 'interfaces',
                      api_endpoint=nb_api_endpoint,
                      api_filter='tag=vrf-svi device=' ~ inventory_hostname,
                      token=nb_api_token) }}"
vnis: "{{ query('netbox.netbox.nb_lookup', 'l2vpns',
                      api_endpoint=nb_api_endpoint,
                      token=nb_api_token) }}"
ls_intfs: "{{ query('netbox.netbox.nb_lookup', 'interfaces',
                      api_endpoint=nb_api_endpoint,
                      api_filter='tag=l3base device=' ~ inventory_hostname,
                      token=nb_api_token) }}"
trunk_intfs: "{{ query('netbox.netbox.nb_lookup', 'interfaces',
                      api_endpoint=nb_api_endpoint,
                      api_filter='mode=tagged device=' ~ inventory_hostname,
                      token=nb_api_token) }}"
ext_intfs: "{{ query('netbox.netbox.nb_lookup', 'interfaces',
                      api_endpoint=nb_api_endpoint,
                      api_filter='name__ic=Ethernet type=virtual device=' ~ inventory_hostname,
                      token=nb_api_token) }}"
loop_intfs: "{{ query('netbox.netbox.nb_lookup', 'interfaces',
                      api_endpoint=nb_api_endpoint,
                      api_filter='name__ic=Loopback type=virtual device=' ~ inventory_hostname,
                      token=nb_api_token) }}"
loop0_addrs: "{{ query('netbox.netbox.nb_lookup', 'ip-addresses',
                              api_endpoint=nb_api_endpoint,
                              api_filter='interface=Loopback0 device=' ~ inventory_hostname, 
                              token=nb_api_token) }}"
router_id: "{{ loop0_addrs[0].value.address | ansible.netcommon.ipaddr('address') }}"
bgp_sessions: "{{ query('netbox.netbox.nb_lookup', 'session',
                          api_endpoint=nb_api_endpoint,
                          plugin='bgp',
                          api_filter='device=' ~ inventory_hostname,
                          token=nb_api_token) }}"
bgp_asn: "{{ bgp_sessions[0].value.local_as.asn }}"
spine01_loop_addrs: "{{ query('netbox.netbox.nb_lookup', 'ip-addresses',
                              api_endpoint=nb_api_endpoint,
                              api_filter='interface=Loopback0 device=n9kv-spine-01',
                              token=nb_api_token) }}"
spine01_loop0: "{{ spine01_loop_addrs[0].value.address | ansible.netcommon.ipaddr('address') }}"
prefixes: "{{ query('netbox.netbox.nb_lookup', 'prefixes',
                api_endpoint=nb_api_endpoint,
                token=nb_api_token) }}"
vrfs_dict: "{{ vrfs | items2dict }}"

